version: '2'
services:
  vault:
    image: hashicorp/vault-enterprise:latest
    network_mode: bridge
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
    environment:
      - VAULT_LICENSE_PATH=/vault/config/vault.license
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
